export interface ScannerManifestEntry {
  name: string
  displayName: string
  category: string
  supportedModes: ("url" | "source")[]
  description: string
  scanTypes: string[]
  typicalDuration: "fast" | "medium" | "slow"
  priority: number
  techIndicators: string[]
  limitations: string
}

export const SCANNER_MANIFEST: ScannerManifestEntry[] = [
  // ── DNS Reconnaissance ─────────────────────────────────────────────────
  {
    name: "subfinder",
    displayName: "Subfinder",
    category: "dns",
    supportedModes: ["url"],
    description: "Passive subdomain enumeration tool that aggregates results from 30+ public data sources including DNS dumpsters, certificate transparency logs, and search engines. Fast and reliable for initial recon.",
    scanTypes: ["Subdomain Enumeration", "Passive DNS Recon", "Asset Discovery"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "domain", "subdomain"],
    limitations: "Only does passive enumeration — no active DNS queries. Completeness depends on data source coverage.",
  },
  {
    name: "amass",
    displayName: "Amass",
    category: "dns",
    supportedModes: ["url"],
    description: "OWASP project — deep DNS enumeration and network mapping. Combines passive sources, active DNS brute-forcing, and recursive subdomain discovery for maximum coverage.",
    scanTypes: ["Deep Subdomain Enumeration", "DNS Brute Force", "Network Mapping", "ASN Discovery"],
    typicalDuration: "slow",
    priority: 3,
    techIndicators: ["http", "https", "domain", "subdomain", "enterprise"],
    limitations: "Heavy tool — long runtime and high memory usage for large targets. May be overkill for small/static sites.",
  },
  {
    name: "assetfinder",
    displayName: "Assetfinder",
    category: "dns",
    supportedModes: ["url"],
    description: "Lightweight subdomain discovery tool that quickly finds related domains and subdomains from various public sources. Ideal as a fast first-pass recon tool.",
    scanTypes: ["Quick Subdomain Discovery", "Related Domain Finding"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "domain"],
    limitations: "Less comprehensive than subfinder or amass — best used as an additional source for broader coverage.",
  },
  {
    name: "shuffledns",
    displayName: "Shuffledns",
    category: "dns",
    supportedModes: ["url"],
    description: "DNS resolver and validator that filters discovered subdomains to resolve-to-live IPs. Eliminates stale/non-resolving DNS entries from enumeration results.",
    scanTypes: ["DNS Resolution", "Subdomain Validation", "Wildcard Detection"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: ["http", "https", "domain"],
    limitations: "Requires a wordlist or pipe input from another DNS enum tool. Only validates — does not discover new subdomains.",
  },

  // ── Port & Network Scanning ───────────────────────────────────────────
  {
    name: "nmap",
    displayName: "Nmap",
    category: "network",
    supportedModes: ["url"],
    description: "Industry-standard port scanner and service detection tool. Scans open ports, detects service versions, OS fingerprinting, and runs NSE scripts for vulnerability detection.",
    scanTypes: ["Port Scanning", "Service Version Detection", "OS Fingerprinting", "NSE Vulnerability Scripts"],
    typicalDuration: "slow",
    priority: 2,
    techIndicators: ["http", "https", "ip", "domain", "enterprise"],
    limitations: "Slow for full port range scans (1-65535). Some NSE scripts may be intrusive. Requires raw socket privileges on some systems.",
  },

  // ── Directory & Content Discovery ─────────────────────────────────────
  {
    name: "ffuf",
    displayName: "Ffuf",
    category: "web",
    supportedModes: ["url"],
    description: "High-performance web fuzzer for directory brute-forcing, parameter discovery, virtual host enumeration, and GET/POST parameter fuzzing. Extremely fast — uses multi-threaded HTTP requests.",
    scanTypes: ["Directory Brute Force", "Parameter Discovery", "VHost Enumeration", "File Extension Fuzzing", "POST Parameter Fuzzing"],
    typicalDuration: "medium",
    priority: 1,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Generates high volume of HTTP requests — may trigger WAF/IDS or rate limiting. Needs good wordlists for best results.",
  },
  {
    name: "gobuster",
    displayName: "Gobuster",
    category: "web",
    supportedModes: ["url"],
    description: "Multi-mode brute force tool supporting directory/file enumeration, DNS subdomain brute-forcing, virtual host discovery, and S3 bucket enumeration.",
    scanTypes: ["Directory Enumeration", "DNS Subdomain Brute Force", "VHost Discovery", "S3 Bucket Enumeration"],
    typicalDuration: "medium",
    priority: 2,
    techIndicators: ["http", "https", "web", "api", "cloud"],
    limitations: "Slower than ffuf for directory scanning due to single-threaded HTTP. Better suited for DNS and VHost brute-forcing.",
  },

  // ── Web Fingerprinting ────────────────────────────────────────────────
  {
    name: "httpx",
    displayName: "Httpx",
    category: "web",
    supportedModes: ["url"],
    description: "HTTP probing and response analysis tool. Sends HTTP requests to detect live hosts, extract response headers, TLS certificate details, technology fingerprints, and favicon hashes.",
    scanTypes: ["HTTP Probing", "Technology Fingerprinting", "Response Header Analysis", "Live Host Detection", "Favicon Hash", "Web Server Detection"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "web"],
    limitations: "Only probes top-level pages — does not crawl. Technology detection relies on response headers and body patterns.",
  },
  {
    name: "whatweb",
    displayName: "WhatWeb",
    category: "web",
    supportedModes: ["url"],
    description: "Web technology identification tool with 1800+ plugins. Recognizes CMS platforms, JavaScript frameworks, web servers, analytics tools, CDNs, and cookie/header signatures.",
    scanTypes: ["CMS Detection", "Framework Identification", "Web Server Detection", "Analytics/CDN Detection", "JavaScript Library Detection"],
    typicalDuration: "medium",
    priority: 3,
    techIndicators: ["http", "https", "web"],
    limitations: "May produce false positives for generic pages. Slower than httpx for bulk scanning due to plugin matching.",
  },

  // ── OSINT & Historical Data ───────────────────────────────────────────
  {
    name: "waybackurls",
    displayName: "Waybackurls",
    category: "osint",
    supportedModes: ["url"],
    description: "Fetch all historical URLs from the Wayback Machine archive for the given domain. Useful for finding old endpoints, backup files, and sensitive paths no longer linked on the live site.",
    scanTypes: ["Wayback Machine URLs", "Historical Path Discovery", "Deleted Page Recovery"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: ["http", "https", "domain"],
    limitations: "Limited to Wayback Machine data only (less coverage than gau which uses multiple sources).",
  },

  // ── WAF Detection ─────────────────────────────────────────────────────
  {
    name: "wafw00f",
    displayName: "WAFw00f",
    category: "web",
    supportedModes: ["url"],
    description: "Web Application Firewall (WAF) detection tool. Sends crafted malicious-looking requests and analyzes responses to identify WAF products from 150+ vendors including CloudFlare, AWS WAF, ModSecurity, Akamai, and F5.",
    scanTypes: ["WAF Detection", "WAF Vendor Identification", "Security Middleware Detection"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Cannot determine WAF ruleset or bypass techniques. May not detect custom/non-standard WAF implementations.",
  },

  // ── Sensitive Info Disclosure ─────────────────────────────────────────
  {
    name: "gitdumper",
    displayName: "GitDumper",
    category: "web",
    supportedModes: ["url"],
    description: "Git repository disclosure detection. Checks if .git directory is exposed on the target and attempts to reconstruct repository structure, including commit history and source code.",
    scanTypes: [".git Exposure Detection", "Source Code Disclosure", "Repository Information Leak"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "web", "git", "source"],
    limitations: "Only works when .git directory is exposed — cannot find hidden or protected repositories. May be blocked by directory listing protection.",
  },

  // ── Web Crawler ─────────────────────────────────────────────────────────
  {
    name: "crawler",
    displayName: "Website Crawler",
    category: "web",
    supportedModes: ["url"],
    description: "Auto-discovery crawler that navigates the target website by following links, extracting all reachable pages, forms, and technologies. Analyzes each discovered page for security issues including missing security headers, form submission security, password exposure, and information disclosure.",
    scanTypes: ["Page Discovery", "Link Extraction", "Form Analysis", "Per-Page Header Check", "Technology Detection", "Sitemap Generation"],
    typicalDuration: "medium",
    priority: 0,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Depth-limited (2 levels) to avoid infinite crawling. Cannot execute JavaScript — single-page apps (SPA) may not be fully crawled. Max 50 pages per target to control scan time.",
  },

  // ── Node.js Native HTTP Security Analyzers ────────────────────────────
  {
    name: "http-headers",
    displayName: "HTTP Security Headers",
    category: "web",
    supportedModes: ["url"],
    description: "Analyzes HTTP response headers for security best practices. Checks for HSTS, CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, and Cache-Control headers. Also extracts Server header, X-Powered-By, and Set-Cookie flags.",
    scanTypes: ["Security Headers Check", "HSTS Detection", "CSP Analysis", "Cookie Security Flags", "Info Disclosure via Headers"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "web"],
    limitations: "Only checks headers from the initial page response — does not crawl subpages. CSP analysis is basic (does not evaluate actual policy effectiveness).",
  },
  {
    name: "cors-detector",
    displayName: "CORS Misconfiguration",
    category: "web",
    supportedModes: ["url"],
    description: "Tests for CORS misconfigurations by sending requests with various Origin headers. Detects wildcard origins, null origin reflection, trusted origin reflection, and credential-enabled CORS.",
    scanTypes: ["CORS Wildcard Detection", "Origin Reflection", "Credentialed CORS", "Preflight Analysis"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Tests only the base URL and common API endpoints. Cannot discover all CORS-protected endpoints without a full crawl.",
  },
  {
    name: "tls-analyzer",
    displayName: "TLS/SSL Analyzer",
    category: "network",
    supportedModes: ["url"],
    description: "Node.js-based TLS analysis that checks certificate validity, expiration, issuer, subject alternative names, protocol version support (TLS 1.0/1.1/1.2/1.3), weak cipher detection, and HSTS configuration.",
    scanTypes: ["Certificate Validation", "TLS Protocol Version Check", "Weak Cipher Detection", "Certificate Expiry Check", "SSL/TLS Misconfiguration"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: ["https", "http", "web"],
    limitations: "Does not perform full cipher scan (limited to Node.js supported ciphers). Certificate chain validation is basic — does not check revocation.",
  },
  {
    name: "form-analyzer",
    displayName: "Form Security Analyzer",
    category: "web",
    supportedModes: ["url"],
    description: "Analyzes HTML forms for security issues including form submission over HTTP (plaintext password), missing autocomplete=off on password fields, password field type detection, and form action pointing to external domains.",
    scanTypes: ["Form Submission Security", "Password Field Analysis", "Autocomplete Check", "External Form Action Detection"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: ["http", "https", "web"],
    limitations: "Only analyzes visible HTML in initial page response. Cannot analyze forms loaded dynamically via JavaScript or iframes.",
  },
  {
    name: "error-analyzer",
    displayName: "Error Page Analyzer",
    category: "web",
    supportedModes: ["url"],
    description: "Probes for information disclosure through error pages. Sends requests to non-existent paths, malformed input, and edge cases to detect stack traces, absolute paths, framework version disclosure, and verbose error messages.",
    scanTypes: ["Path Disclosure", "Stack Trace Detection", "Framework Version Leak", "Debug Mode Detection"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Cannot distinguish between custom error pages and default ones without knowing the framework. Some apps return generic error pages regardless.",
  },
  {
    name: "favicon-analyzer",
    displayName: "Favicon Analyzer",
    category: "web",
    supportedModes: ["url"],
    description: "Fetches and hashes the site's favicon.ico, then uses the hash to identify the technology framework and find related servers via Shodan-like hash matching. Useful for technology identification and asset correlation.",
    scanTypes: ["Favicon Hash Calculation", "Technology Identification via Favicon", "Organization Asset Correlation"],
    typicalDuration: "fast",
    priority: 3,
    techIndicators: ["http", "https", "web"],
    limitations: "Only works if the site has a favicon.ico. Many modern SPAs use inline SVGs instead of favicon files. Hash matching requires a reference database.",
  },
  {
    name: "third-party-deps",
    displayName: "Third-Party Dependency Check",
    category: "web",
    supportedModes: ["url"],
    description: "Analyzes loaded JavaScript libraries and external resources for known vulnerable versions. Checks CDN-loaded scripts, CSS frameworks, and JavaScript libraries against a vulnerability database.",
    scanTypes: ["Known Vulnerable JS Libraries", "Outdated Frontend Dependencies", "CDN Dependency Check", "SRI Integrity Check"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: ["http", "https", "web"],
    limitations: "Only checks front-end loaded libraries — cannot check server-side dependencies. Limited to libraries with known version signatures.",
  },

  // ── Existing Source-Mode Scanners ─────────────────────────────────────
  {
    name: "semgrep",
    displayName: "Semgrep",
    category: "sast",
    supportedModes: ["source"],
    description: "Multi-language SAST scanner that analyzes source code against 2000+ security rules. Supports JavaScript, TypeScript, Python, Java, Go, Rust, Ruby, PHP, C#, Swift, Kotlin, and more.",
    scanTypes: ["SQL Injection", "XSS", "Command Injection", "Path Traversal", "Insecure Crypto", "Prototype Pollution", "Hardcoded Secrets", "Insecure Deserialization", "SSRF", "Open Redirect"],
    typicalDuration: "medium",
    priority: 1,
    techIndicators: [".js", ".ts", ".jsx", ".tsx", ".py", ".java", ".go", ".rs", ".rb", ".php", ".cs", ".kt", ".swift"],
    limitations: "Only analyzes source code, not running applications. Requires the target to be a source code directory.",
  },
  {
    name: "gitleaks",
    displayName: "Gitleaks",
    category: "secret",
    supportedModes: ["source"],
    description: "Secret detection scanner that identifies hardcoded credentials, API keys, tokens, private keys, and other sensitive data in source code repositories.",
    scanTypes: ["API Keys", "Private Keys", "Tokens", "Passwords", "Database Credentials", "Cloud Provider Secrets", "JWT Tokens"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: [".env", "id_rsa", "id_ed25519", ".pem", "credentials", "secret", "token", "api_key", "password"],
    limitations: "May produce false positives for example/test credentials. Best used as a first-pass indicator.",
  },
  {
    name: "bandit",
    displayName: "Bandit",
    category: "sast",
    supportedModes: ["source"],
    description: "Python-specific SAST scanner that detects common security issues in Python code including injection flaws, hardcoded passwords, insecure imports, and unsafe eval/exec usage.",
    scanTypes: ["Code Injection", "Hardcoded Password", "Insecure Import", "Shell Injection", "Temporary File Issues", "Assert Violation", "Request without Verification"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: [".py", "requirements.txt", "Pipfile", "setup.py"],
    limitations: "Python only. Only analyzes source code, not dependencies or running applications.",
  },
  {
    name: "npm-audit",
    displayName: "npm audit",
    category: "dependency",
    supportedModes: ["source"],
    description: "JavaScript/TypeScript dependency vulnerability scanner. Analyzes package-lock.json or node_modules to identify known CVEs in npm packages.",
    scanTypes: ["Known CVEs in Dependencies", "Supply Chain Vulnerabilities", "Malicious Packages"],
    typicalDuration: "fast",
    priority: 3,
    techIndicators: ["package.json", "package-lock.json", "node_modules", "npm", "yarn.lock"],
    limitations: "Only scans JavaScript/TypeScript projects. Requires package-lock.json or node_modules to exist.",
  },
  {
    name: "pip-audit",
    displayName: "pip-audit",
    category: "dependency",
    supportedModes: ["source"],
    description: "Python dependency vulnerability scanner. Audits pip packages against the Python Advisory Database to identify known CVEs.",
    scanTypes: ["Known CVEs in Dependencies", "Supply Chain Vulnerabilities"],
    typicalDuration: "fast",
    priority: 3,
    techIndicators: ["requirements.txt", "Pipfile", "Pipfile.lock", "setup.py", "pyproject.toml"],
    limitations: "Only scans Python projects. Requires requirements.txt or installed packages.",
  },
  {
    name: "checkov",
    displayName: "Checkov",
    category: "filesystem",
    supportedModes: ["source"],
    description: "Infrastructure-as-Code (IaC) security scanner. Analyzes Terraform, CloudFormation, Kubernetes, Dockerfile, and Helm charts for security misconfigurations.",
    scanTypes: ["IaC Misconfiguration", "Docker Security", "K8s Security", "Cloud Security", "Network Exposure", "IAM Misconfiguration"],
    typicalDuration: "medium",
    priority: 4,
    techIndicators: [".tf", "Dockerfile", "k8s", "kubernetes", "helm", "cloudformation", "docker-compose"],
    limitations: "Only scans infrastructure configuration files. Does not scan application source code.",
  },
  {
    name: "trivy",
    displayName: "Trivy",
    category: "filesystem",
    supportedModes: ["source"],
    description: "Comprehensive filesystem vulnerability scanner. Detects known CVEs in OS packages, language-specific dependencies, IaC misconfigurations, and secret exposure.",
    scanTypes: ["OS Package CVEs", "Library CVEs", "IaC Misconfigurations", "Exposed Secrets", "License Issues"],
    typicalDuration: "medium",
    priority: 2,
    techIndicators: ["Dockerfile", "Gemfile", "pom.xml", "build.gradle", "go.mod", "Cargo.toml", "composer.json"],
    limitations: "First run downloads vulnerability database which can be slow. Requires network access for database updates.",
  },
  {
    name: "nuclei",
    displayName: "Nuclei",
    category: "filesystem",
    supportedModes: ["url", "source"],
    description: "Template-based vulnerability scanner that tests against thousands of known CVEs and security misconfigurations using YAML templates. Supports URL scanning for live web apps and file-based scanning for source code directories.",
    scanTypes: ["Known CVEs", "Web Misconfigurations", "Exposed Panels", "Technology Fingerprinting", " Missing Headers", "Open S3 Buckets", "Subdomain Takeover"],
    typicalDuration: "medium",
    priority: 2,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Network-bound, depends on template database updates. May generate traffic that triggers WAF/IDS.",
  },
  {
    name: "wapiti",
    displayName: "Wapiti",
    category: "filesystem",
    supportedModes: ["url"],
    description: "DAST (Dynamic Application Security Testing) scanner that crawls web applications and tests for common web vulnerabilities including SQL injection, XSS, file inclusion, SSRF, XXE, and CRLF injection.",
    scanTypes: ["SQL Injection", "XSS", "File Inclusion", "Command Execution", "SSRF", "XXE", "LDAP Injection", "CRLF Injection", "Backup File Disclosure", "HTAccess Bypass", "Method Enumeration", "Open Redirect"],
    typicalDuration: "slow",
    priority: 3,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Slower due to crawling and active testing. May miss JavaScript-heavy SPA vulnerabilities. Some modules may cause application disruption.",
  },
  {
    name: "sqlmap",
    displayName: "SQLMap",
    category: "filesystem",
    supportedModes: ["url"],
    description: "Automated SQL injection detection and exploitation tool. Detects and exploits SQL injection vulnerabilities, supports boolean-based, time-based, error-based, and UNION query techniques.",
    scanTypes: ["SQL Injection", "Boolean-Based Blind SQLi", "Time-Based Blind SQLi", "Error-Based SQLi", "UNION Query SQLi", "Stacked Queries", "Out-of-Band SQLi"],
    typicalDuration: "slow",
    priority: 4,
    techIndicators: ["http", "https", "web", "api", "sql", "database"],
    limitations: "Slow due to extensive testing. Requires at least one injectable parameter to be useful. Some techniques may cause database disruption.",
  },
  {
    name: "ai-scanner",
    displayName: "AI Scanner",
    category: "ai",
    supportedModes: ["url", "source"],
    description: "AI-powered code analysis using DeepSeek LLM. Crawls web pages or reads source code and uses AI to identify security vulnerabilities, logic flaws, and architectural issues that traditional scanners might miss.",
    scanTypes: ["Logic Flaws", "Business Logic Vulnerabilities", "Authentication Issues", "Authorization Issues", "Architecture Risks", "Compliance Issues", "OWASP Top 10", "Custom Logic Vulnerabilities"],
    typicalDuration: "slow",
    priority: 5,
    techIndicators: ["code", "logic", "architecture"],
    limitations: "Depends on DeepSeek API availability and quality of code context provided. Cannot find all vulnerability types that specialized tools can. Slower due to API call.",
  },
]

export function getManifestForMode(mode: "url" | "source"): ScannerManifestEntry[] {
  return SCANNER_MANIFEST.filter(e => e.supportedModes.includes(mode))
}
