export interface ScannerManifestEntry {
  name: string
  displayName: string
  category: string
  supportedModes: ("url" | "source")[]
  description: string
  scanTypes: string[]
  typicalDuration: "fast" | "medium" | "slow"
  priority: number
  techIndicators: string[]
  limitations: string
}

export const SCANNER_MANIFEST: ScannerManifestEntry[] = [
  // ── Source-Mode Scanners ──────────────────────────────────────────────
  {
    name: "semgrep",
    displayName: "Semgrep",
    category: "sast",
    supportedModes: ["source"],
    description: "Multi-language SAST scanner that analyzes source code against 2000+ security rules. Supports JavaScript, TypeScript, Python, Java, Go, Rust, Ruby, PHP, C#, Swift, Kotlin, and more.",
    scanTypes: ["SQL Injection", "XSS", "Command Injection", "Path Traversal", "Insecure Crypto", "Prototype Pollution", "Hardcoded Secrets", "Insecure Deserialization", "SSRF", "Open Redirect"],
    typicalDuration: "medium",
    priority: 1,
    techIndicators: [".js", ".ts", ".jsx", ".tsx", ".py", ".java", ".go", ".rs", ".rb", ".php", ".cs", ".kt", ".swift"],
    limitations: "Only analyzes source code, not running applications. Requires the target to be a source code directory.",
  },
  {
    name: "gitleaks",
    displayName: "Gitleaks",
    category: "secret",
    supportedModes: ["source"],
    description: "Secret detection scanner that identifies hardcoded credentials, API keys, tokens, private keys, and other sensitive data in source code repositories.",
    scanTypes: ["API Keys", "Private Keys", "Tokens", "Passwords", "Database Credentials", "Cloud Provider Secrets", "JWT Tokens"],
    typicalDuration: "fast",
    priority: 1,
    techIndicators: [".env", "id_rsa", "id_ed25519", ".pem", "credentials", "secret", "token", "api_key", "password"],
    limitations: "May produce false positives for example/test credentials. Best used as a first-pass indicator.",
  },
  {
    name: "bandit",
    displayName: "Bandit",
    category: "sast",
    supportedModes: ["source"],
    description: "Python-specific SAST scanner that detects common security issues in Python code including injection flaws, hardcoded passwords, insecure imports, and unsafe eval/exec usage.",
    scanTypes: ["Code Injection", "Hardcoded Password", "Insecure Import", "Shell Injection", "Temporary File Issues", "Assert Violation", "Request without Verification"],
    typicalDuration: "fast",
    priority: 2,
    techIndicators: [".py", "requirements.txt", "Pipfile", "setup.py"],
    limitations: "Python only. Only analyzes source code, not dependencies or running applications.",
  },
  {
    name: "npm-audit",
    displayName: "npm audit",
    category: "dependency",
    supportedModes: ["source"],
    description: "JavaScript/TypeScript dependency vulnerability scanner. Analyzes package-lock.json or node_modules to identify known CVEs in npm packages.",
    scanTypes: ["Known CVEs in Dependencies", "Supply Chain Vulnerabilities", "Malicious Packages"],
    typicalDuration: "fast",
    priority: 3,
    techIndicators: ["package.json", "package-lock.json", "node_modules", "npm", "yarn.lock"],
    limitations: "Only scans JavaScript/TypeScript projects. Requires package-lock.json or node_modules to exist.",
  },
  {
    name: "pip-audit",
    displayName: "pip-audit",
    category: "dependency",
    supportedModes: ["source"],
    description: "Python dependency vulnerability scanner. Audits pip packages against the Python Advisory Database to identify known CVEs.",
    scanTypes: ["Known CVEs in Dependencies", "Supply Chain Vulnerabilities"],
    typicalDuration: "fast",
    priority: 3,
    techIndicators: ["requirements.txt", "Pipfile", "Pipfile.lock", "setup.py", "pyproject.toml"],
    limitations: "Only scans Python projects. Requires requirements.txt or installed packages.",
  },
  {
    name: "checkov",
    displayName: "Checkov",
    category: "filesystem",
    supportedModes: ["source"],
    description: "Infrastructure-as-Code (IaC) security scanner. Analyzes Terraform, CloudFormation, Kubernetes, Dockerfile, and Helm charts for security misconfigurations.",
    scanTypes: ["IaC Misconfiguration", "Docker Security", "K8s Security", "Cloud Security", "Network Exposure", "IAM Misconfiguration"],
    typicalDuration: "medium",
    priority: 4,
    techIndicators: [".tf", "Dockerfile", "k8s", "kubernetes", "helm", "cloudformation", "docker-compose"],
    limitations: "Only scans infrastructure configuration files. Does not scan application source code.",
  },
  {
    name: "trivy",
    displayName: "Trivy",
    category: "filesystem",
    supportedModes: ["source"],
    description: "Comprehensive filesystem vulnerability scanner. Detects known CVEs in OS packages, language-specific dependencies, IaC misconfigurations, and secret exposure.",
    scanTypes: ["OS Package CVEs", "Library CVEs", "IaC Misconfigurations", "Exposed Secrets", "License Issues"],
    typicalDuration: "medium",
    priority: 2,
    techIndicators: ["Dockerfile", "Gemfile", "pom.xml", "build.gradle", "go.mod", "Cargo.toml", "composer.json"],
    limitations: "First run downloads vulnerability database which can be slow. Requires network access for database updates.",
  },
  {
    name: "nuclei",
    displayName: "Nuclei",
    category: "filesystem",
    supportedModes: ["source"],
    description: "Template-based vulnerability scanner that tests against thousands of known CVEs and security misconfigurations using YAML templates. Scans source code directories for file-based security issues.",
    scanTypes: ["Known CVEs", "Web Misconfigurations", "Exposed Panels", "Missing Headers", "Open S3 Buckets"],
    typicalDuration: "medium",
    priority: 2,
    techIndicators: ["http", "https", "web", "api"],
    limitations: "Network-bound, depends on template database updates. May require network access for template downloads.",
  },
  {
    name: "dependency-check",
    displayName: "Dependency-Check",
    category: "dependency",
    supportedModes: ["source"],
    description: "OWASP Dependency-Check — industry-standard Software Composition Analysis (SCA) tool. Scans project dependencies for known CVEs across Java (Maven, Gradle), .NET, Python, Ruby, Node.js, Go, Rust (Cargo), and C/C++. Identifies vulnerable library versions and suggests upgrades.",
    scanTypes: ["Java Maven/Gradle CVEs", "Go Module CVEs", "Rust Cargo CVEs", ".NET NuGet CVEs", "C/C++ Library CVEs", "Known Vulnerable Components"],
    typicalDuration: "medium",
    priority: 3,
    techIndicators: ["pom.xml", "build.gradle", "go.mod", "Cargo.toml", ".csproj", "packages.config"],
    limitations: "Requires Java Runtime (JRE) 8+. First run downloads NVD database which can take 10+ minutes. Use --noupdate flag for subsequent runs to skip database updates.",
  },
  {
    name: "cve-cpp",
    displayName: "C/C++ CVE Scanner",
    category: "dependency",
    supportedModes: ["source"],
    description: "C/C++ dependency vulnerability scanner. Parses Conan (conanfile.txt, conanfile.py), vcpkg (vcpkg.json), and CMakeLists.txt to extract library dependencies, then queries the OSV.dev API for known CVEs. No external tool required.",
    scanTypes: ["Conan Package CVEs", "vcpkg Library CVEs", "CMake Dependency Issues", "C/C++ Library CVEs", "Unpinned Version Warnings"],
    typicalDuration: "medium",
    priority: 3,
    techIndicators: ["conanfile.txt", "conanfile.py", "vcpkg.json", "CMakeLists.txt", ".cpp", ".c", ".h", ".hpp"],
    limitations: "Requires network access for OSV.dev API queries. vcpkg dependencies without pinned versions cannot be checked for CVEs. CMake find_package detection is informational only.",
  },
  {
    name: "swift",
    displayName: "Swift Package Scanner",
    category: "dependency",
    supportedModes: ["source"],
    description: "Swift Package Manager dependency vulnerability scanner. Parses Package.resolved and Package.swift to extract exact dependency versions, then queries the OSV.dev API for known CVEs. No external tool required.",
    scanTypes: ["Swift Package CVEs", "SPM Dependency Vulnerabilities", "Unresolved Dependency Warnings"],
    typicalDuration: "medium",
    priority: 3,
    techIndicators: ["Package.swift", "Package.resolved", ".swift"],
    limitations: "Requires network access for OSV.dev API queries. Most accurate when Package.resolved is present (run 'swift package resolve' first).",
  },
  {
    name: "ai-scanner",
    displayName: "AI Scanner",
    category: "ai",
    supportedModes: ["source"],
    description: "AI-powered code analysis using DeepSeek LLM. Reads source code and uses AI to identify security vulnerabilities, logic flaws, and architectural issues that traditional scanners might miss.",
    scanTypes: ["Logic Flaws", "Business Logic Vulnerabilities", "Authentication Issues", "Authorization Issues", "Architecture Risks", "Compliance Issues", "OWASP Top 10", "Custom Logic Vulnerabilities"],
    typicalDuration: "slow",
    priority: 5,
    techIndicators: ["code", "logic", "architecture"],
    limitations: "Depends on DeepSeek API availability and quality of code context provided. Cannot find all vulnerability types that specialized tools can. Slower due to API call.",
  },
]
